modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="mixed_ore"
version="1.0.44"
displayName="Mixed_Ore"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/mixedore/files"
logoFile="logo.png"
authors="Jin1358, MCreator"
description='''
This mod adds mixed ores and corresponding tools
'''

[[dependencies.mixed_ore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




